### ISSUE TITLE
NPM install

### ISSUE THREAD

**Issue by oneplatforms-timbrand** [geekhybrid/tree-vue#4]
Hi there,

I'd like to try this component out but I can't find how to install this as a NPM package in de documentation. Is this possible or what is the way to install this?

Greetings

**Comment by geekhybrid** [comment]
Hey @oneplatforms-timbrand,

Thanks for pointing out the missing info in the docs. I'll update the docs immediately, but in the meantime please run `npm i v-tree-vue`.

**Comment by oneplatforms-timbrand** [comment]
Thanks alot! 🙏
