### ISSUE TITLE
CDN Version

### ISSUE THREAD

**Issue by tgraupmann** [geekhybrid/tree-vue#6]
Do you have a CDN version? I'll run it through browserify so I can use it outside of NodeJS in plain JS.

Also a live demo would be great.

You have one of the best Vue treeview components that I've seen!

I did `npm install` but I'm getting typescript errors even though the paths are specified in `tsconfig.json`. I get the same errors in the command-prompt and vs code.

You have src in the path, what gives???

```
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
```

![image](https://user-images.githubusercontent.com/931421/136602570-22fee7f9-3ab8-40f0-a630-66d4e0124778.png)

Okay I did
```
npm run build
```

The output `dist/index.html` had absolute paths that I had to switch to relative paths.

```
/css/app.b6216f1d.css
```

It needs a webpack config to make the paths relative.

I hacked it with a script on the index page.

```
<script>
  let imgs = document.querySelectorAll('img');
  for (index in imgs) {
    let img = imgs[index];
    if (img.src) {
      let rmIndex = img.src.indexOf('/img');
      img.src = img.src.substring(rmIndex + 1);
    }
  }
</script>
```

The demo works, but I can't use it unless I can browserify the tree-view component.

**Comment by geekhybrid** [comment]
@tgraupmann  thanks for spotting these issues and the compliments on the work.

Feel free to email me at hocahaenyi17@gmail.com so we could discuss what your use cases are and how we can improve this to meet them.

In the meantime, @ikeohachidi can you please have a look at this? 😁

**Comment by ikeohachidi** [comment]
@geekhybrid I'll check it out

**Comment by geekhybrid** [comment]
Hi @tgraupmann,

This is coming a lot later than I would've hoped for, but have you been able to get your use case working?

**Comment by tgraupmann** [comment]
I was new to webpack when I posted this. I probably know enough now that I can make the `npm run build` dist output work for me.

**Comment by geekhybrid** [comment]
> I was new to webpack when I posted this. I probably know enough now that I can make the `npm run build` dist output work for me.

Awesome! 🎆 

I know better how to publish npm packages. If you ever need to, you can checkout `vue3-tree-vue` for the vue 3 version.

If you have any specific use cases you will like to cover, please let me know. This time, I won't take two forevers. 😄 

Closing this issue now.
