### ISSUE TITLE
How to expand all nodes without knowing the types

### ISSUE THREAD

**Issue by SciManJD** [geekhybrid/tree-vue#7]
Is there an easy way to expand all nodes in the tree without knowing the types? My problem is the following. I read the tree structure from the server, but the types are not know in the WEB application. I don't want to fix them, because new types can appear later and this will lead to update of the WEB application. I tried the following workaround, but I don't like it, therefore I'm searching a better solution. In the lifetime hook "created" I read the tree structure (needs to be blocking), then I search all the types that are received, I create dynamically the array that is given to the property "expandedTypes" and set the property "items". This works, but I want to avoid this blocking read. I tried to make it asynchronous (with fetch), but then I had different problems. It seems that I set "items" before "expandedTypes", the expansion is not applied. Also if I do the correct sequence, but on "mounted", the also the expansion is not made. What is the right way to do this?

**Comment by geekhybrid** [comment]
@SciManJD , I suppose you want to do this on the vue3 version of the project?

If yes, please create an issue here https://github.com/geekhybrid/vue3-tree-vue, and it will be looked into. :)
